### ISSUE TITLE
Method to Create a new model file

### ISSUE THREAD

**Issue by russlooker** [llooker/pylookml#26]
Currently there does not exist an ability to create a new model file from scratch, as experienced by Hugo.

**Comment by hugoselbie** [comment]
This might be evidenced of a larger issue, it seems like there is not an easy way to create generic lookml files in general from scratch in pylookml, @jdemartino78 and I have experienced this issue where if you try to create a model file or a non specific `.lkml` file there is no method to support this. 

example a file that just stores datagroups, just stores accessgrants etc. 

Seems like the logic is that you have very tight integration into files that have already been created in git, but not especially easy to create large numbers of files and deploy to git.

**Comment by russlooker** [comment]
@hugoselbie 
fixed in version 3.0, just merged and pushed to pypi
