### ISSUE TITLE
Cannot get lookml files with double-byte characters

### ISSUE THREAD

**Issue by YSArch** [llooker/pylookml#37]
in lookml.py, it's hardcoded decode by 'ascii'.

#Parse Step: Github content is returned base64 encoded
 **data = base64.b64decode(f.content).decode('ascii')**

**Comment by russlooker** [comment]
This is now fixed in the latest release on pypi version 3.0.0
I saw that was only for github projects I believe, but it should be all utf-8 compatible now
try a 
`pip uninstall lookml`
`pip install lookml`
