### ISSUE TITLE
Model file parsing by pylookml

### ISSUE THREAD

**Issue by rchakravorty** [llooker/pylookml#40]
I am currently looking on views creation by pylookml and I have successfully created .view files with pylookml. In order to expose these views as explores I am not getting any documentation of working with looker model via pylookml. Please suggest

**Comment by russlooker** [comment]
sorry for the slow reply, just finished a major rewrite. 
run a 
`pip uninstall lookml`
`pip install lookml`
then after you've connected to your project you can run:
```python
modelFile = proj.file('my_model.model.lkml') 
for e in modelFile.explores:
    print(e)
modelFile + 'explore: foo {}'
```
etc
Let me know how it goes!
