### ISSUE TITLE
ModuleNotFoundError: No module named 'dataclasses'

### ISSUE THREAD

**Issue by siavashrad** [llooker/pylookml#41]
import lookml was working fine with 3.6.12 until Jan 08.
Started failing with below error on Jan 09
`ModuleNotFoundError: No module named 'dataclasses'`

I understand there were some changes in https://github.com/joshtemple/lkml on Jan 9th that might be related.
Just wondering why there is no new release with these changes and are all part of lookml 2.0.0?

**Comment by russlooker** [comment]
just release version 3.0.0 on pip.
can you try a pip uninstall lookml / pip install lookml and see if your issue is fixed?
(and apologies on the delay, 3.0.0 was a total re-write)
