### ISSUE TITLE
Error when dimension name includes numbers

### ISSUE THREAD

**Issue by marianoteehan** [llooker/pylookml#43]
Hello, simple question, some of my database columns have numbers in their names and I've noticed lookml doesn't like them.  Is this by design?
    
This works fine:
    
    lookml.Dimension('dimension: street {}')

This gives an error:
    
    lookml.Dimension('dimension: street1 {}')

    Exception: dimension: street1 {} does not match a view: name {} or lookml name pattern

**Comment by russlooker** [comment]
I'll take a look at this this evening, believed I had permitted numbers in the regex validator. Will ping you here when I push a new version to pypi

**Comment by russlooker** [comment]
@marianoteehan  it is now fixed in version 3.0.3 available in pip, run a quick upgrade. Thank you so much for logging this 👍

**Comment by marianoteehan** [comment]
Thanks for the quick fix!
